##--------------------------------------------------------------------
## rmqtt-http-api
##--------------------------------------------------------------------

# See more keys and their definitions at https://github.com/rmqtt/rmqtt/blob/master/docs/en_US/http-api.md

##Number of worker threads
workers = 1
## Max Row Limit
max_row_limit = 10_000
## HTTP Listener
http_laddr = "0.0.0.0:6060"
## Indicates whether to print HTTP request logs
http_request_log = false
## If set, will check request header Authorization value == Bearer $http_bearer_token, default value is undefined
#http_bearer_token = bearer_token

##Message expiration time, 0 means no expiration
message_expiry_interval = "5m"
